# Changes do not take effect until the astro server (npm run dev) is restarted 
# if NODE_ENV is 'development' then site and base are overridden by VITE_SITE and VITE_BASE (See config.ts)
site:
  name: The Dissenter
  site: 'https://www.thedissenter.net/'
  base: '/'
  trailingSlash: true

  googleSiteVerificationId: null

# Re-use robot index settings using yaml &anchor (here) and *alias (below)
defaults: &robotsdefault
    index  : false
    follow : false

# Default SEO metadata
metadata:
  title:
    default: The Dissenter
    template: '%s — The Dissenter Podcast'
  description: "My name is Ricardo Lopes, and I'm from Portugal. Thank you for visiting my podcast. Over the past few years, I have conducted and released more than 800 interviews and talks with experts and academics from a variety of areas and disciplines, ranging from the Arts and Philosophy to the Social Sciences and Biology. You will certainly find a subject of your interest covered here. New interviews are released on Mondays, Thursdays, and Fridays."
  robots: *robotsdefault
  openGraph:
    site_name: The Dissenter
    images:
      - url: '~/assets/images/thedissenter-opengraph-1200x630.jpg'
        width: 1200
        height: 630
    type: website
  # twitter:
  #   handle: '@onwidget'
  #   site: '@onwidget'
  #   cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 10

    post:
      isEnabled: true
      permalink: 'podcast/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots: *robotsdefault

    list:
      isEnabled: true
      pathname: 'podcast' # Blog main path, you can change this to "articles" (/articles)
      robots: *robotsdefault

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots: *robotsdefault

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

analytics:
  vendors:
    googleAnalytics:
      id: "G-FVW89X23D4" # or null
      partytown: false
      vanillacookieconsent: true

ui:
  // inCharge: Disable dark mode
  theme: 'light:only' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"

  tokens:
    default:
      fonts:
        sans: InterVariable
        serif: var(--ph-font-sans)
        heading: var(--ph-font-sans)
      colors:
        default: rgb(16 16 16)
        heading: rgb(0 0 0)
        muted: rgb(40 40 40)
        bgPage: rgb(255 255 255)
        primary: rgb(0 124 220)
        secondary: rgb(30 58 138)
        accent: rgb(109 40 217)
        info: rgb(119 182 234)
        success: rgb(54 211 153)
        warning: rgb(251 189 35)
        error: rgb(248 114 114)
        link: var(--ph-color-primary)
        linkActive: var(--ph-color-link)
    dark:
      fonts: {}
      colors:
        default: rgb(247, 248, 248)
        heading: rgb(247, 248, 248)
        muted: rgb(200, 188, 208)
        bgPage: rgb(3 6 32)
        primary: rgb(29 78 216)
        secondary: rgb(30 58 138)
        accent: rgb(135 77 2267)
        info: rgb(58 191 248)
        success: rgb(54 211 153)
        warning: rgb(251 189 35)
        error: rgb(248 114 114)
        link: var(--ph-color-primary)
        linkActive: var(--ph-color-link)
